"""conversation states stored in telegram user_data."""

AWAIT_SHEET_URL = "await_sheet_url"
AWAIT_NICKNAME = "await_nickname"
AWAIT_INCOME_NAME = "await_income_name"
AWAIT_INCOME_AMOUNT = "await_income_amount"
AWAIT_INCOME_CONFIRM = "await_income_confirm"
AWAIT_OUTCOME_NAME = "await_outcome_name"
AWAIT_OUTCOME_UNITS = "await_outcome_units"
AWAIT_OUTCOME_PRICE = "await_outcome_price"
AWAIT_OUTCOME_AMOUNT = "await_outcome_amount"
AWAIT_OUTCOME_CONFIRM = "await_outcome_confirm"
AWAIT_DELETE_DATE = "await_delete_date"
AWAIT_DELETE_NAME = "await_delete_name"
AWAIT_DELETE_TYPE = "await_delete_type"
AWAIT_DELETE_PICK = "await_delete_pick"
AWAIT_DELETE_CONFIRM = "await_delete_confirm"
AWAIT_CURRENCY = "await_currency"
AWAIT_SETTINGS_NICKNAME = "await_settings_nickname"
AWAIT_SHEET_CONFIRM = "await_sheet_confirm"
AWAIT_SETTINGS_MENU = "await_settings_menu"
AWAIT_LANGUAGE = "await_language"
AWAIT_MONTH_PICK = "await_month_pick"
